name: Connect to EC2 (Test)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup SSH key
      run: |
        echo "${{ vars.EC2_SSH_KEY }}" > deploy_key.pem
        chmod 600 deploy_key.pem

    - name: Connect to EC2 via SSH
      run: |
        ssh -i deploy_key.pem -o StrictHostKeyChecking=no ${{ vars.EC2_USERNAME }}@${{ vars.EC2_HOST }} "echo 'Connected successfully to EC2!'"
      
    - name: Cleanup
      run: |
        rm deploy_key.pem
