name: Connect to EC2 (Test)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup SSH key from base64
      run: |
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        echo "${{ vars.EC2_SSH_KEY_BASE64 }}" | base64 -d > ~/.ssh/deploy_key
        chmod 600 ~/.ssh/deploy_key
        
        # Проверяем ключ
        ssh-keygen -l -f ~/.ssh/deploy_key || echo "Key check failed, but continuing..."

    - name: Connect to EC2 via SSH
      run: |
        ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no -v ${{ vars.EC2_USERNAME }}@${{ vars.EC2_HOST }} "echo 'Connected successfully to EC2!'"

    - name: Cleanup
      run: |
        rm -f ~/.ssh/deploy_key